// this codes are used to send requests to the server
module.exports = {
    FILE_REQUEST: 1,
    UPDATE_REQUEST: 2,
    NEW_FILE_REQUEST: 3,
    SIGNUP_REQUEST: 4,
    LOGIN_REQUEST: 5,
    NEW_FOLDER_REQUEST: 6,
    GET_FILES_AND_FOLDERS_REQUEST: 7,
    DISCONNECT_FROM_FILE_REQUEST: 8,
    GET_SHARE_CODE: 9,
    CONNECT_TO_SHARED_OBJECT_REQUEST: 10,
    GET_SHARED_FILES_AND_FOLDERS_REQUEST: 11,
    GET_FILES_REQUEST: 12,
    GET_FILE_SHARES: 13,
    REMOVE_SHARES: 14,
    DOWNLOAD_FILES: 15,
    DELETE_SELECTION: 16
};